### ISSUE TITLE
Functionalities from 5.1. not present in 5.2?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1938]
besides search issues listed at https://github.com/BetaMasaheft/Documentation/issues/3029

- [x] https://github.com/BetaMasaheft/Documentation/issues/1691

- [x] https://github.com/BetaMasaheft/Documentation/issues/1602 (sparql searches do not work, cp. https://github.com/BetaMasaheft/Documentation/issues/1972 , https://github.com/BetaMasaheft/Documentation/issues/2047)

- [x] https://github.com/BetaMasaheft/Documentation/issues/1631

- [ ] graphs in graphs and relations

- [x] tokenizing corresp in bibliography https://github.com/BetaMasaheft/Documentation/issues/2793
- [x] locus when a facs with manifest is present should resolve to a link to image (now not working and suppressed) (see https://github.com/BetaMasaheft/Documentation/issues/2097 https://github.com/BetaMasaheft/Documentation/issues/2230)

- [x] view of places and persons - names should appear in the same way as they do for works (with transcription from corresp in brackets), as it used to be
snapshots from a 2018 app version 

![Image](https://github.com/user-attachments/assets/f95ae08a-da5e-41c6-9daa-c325493ebf5e)

![Image](https://github.com/user-attachments/assets/f55d567f-86d4-4c1c-bcb2-1f361b5114ae)

done in https://github.com/BetaMasaheft/BetMas/commit/456a0cb1c1677a65fa48290ddf37982b5c29c42f

- [x] view of institutions - boxes should be moved back where they used to be

- [x] maps of marked up places 
here in 2018

![Image](https://github.com/user-attachments/assets/ed843a27-4ce0-4363-812d-907f33096f20)
