### ISSUE TITLE
Encoding of miniatures

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#641]
There are two items in the Frankfurt collection which contain only miniatures (Ms. or. 111 and 112) - should these be given any content related keywords ("ChristianLiterature" and "Hagiography", for instance), or do we reserve these keywords for texts (as indicated by the current definitions in the schema)?

**Comment by MassimoVilla** [comment]
I would add "Hagiography": also pictorial representations are useful for those who investigate the traditions around a certain saint. I am personally less convinced as to "ChristianLiterature".
We should therefore broaden a bit the definition for "Hagiography" in the schema.

**Comment by PietroLiuzzo** [comment]
This is a content related question on which I have nothing to say

**Comment by Gnisci** [comment]
My two cents, the images may not be related to hagiography if they show, for instance, episodes relating to the life of Jesus?

**Comment by thea-m** [comment]
Thank you, Jacopo!
Our keywords until now mainly relate to literary works, so we don't have "figure". There hasn't been a lot of work done on decorations.
You can have a look at the keywords here:
http://betamasaheft.eu/authority-files/list
(what we mean by "keyword" in this discussion is listed there under "Subjects")
An overview of the currently encoded decorations can be found here:
http://betamasaheft.eu/decorations
We'd be of course happy to hear your comments or suggestions!

I agree with @MassimoVilla that searching and finding pictorial representations of certain persons or topics could be very useful. I'm not sure whether it makes more sense to broaden the current definitions to include decorations, or to add new art-related keywords. 
@Gnisci , maybe you have some ideas as to how you would want to search for images etc. in the beta masaheft app?

Maybe related: in the authority files http://betamasaheft.eu/authority-files/list we do have "Art Themes" keywords, but these have never been used. Do they originate in the Ethiospare guidelines? @DenisNosnitsin1970

**Comment by Gnisci** [comment]
Thanks for getting back to me, and sorry for belated response, I wanted to spend time getting a better sense of the (amazing) work you are doing and ask a few things to Pietro before getting back to you.

I see many of the manuscripts already include some information on the decoration. In addition to what is included, the kind of things I would wish to look in beta masaheft as an art historian would be miniatures by: 
**1. Themes** (e.g. Virgin and Child)
**2. Iconographic Types** (e.g. S. Maria Maggiore-Type)
**3. Styles** (e.g. Gunda Gunde)
**4. Artist/Workshop,** if known (e.g. Anfin), but I would still provide an artist identifier for works that can be attributed to the same painter (more common from the Gondarine period, but not unattested for earlier period); the reason I would overlap artist/workshop is because certain artists consistently worked as a group (so one consistently finds multiple hands in a single work)
**5. Date** (e.g. Postaksumite II)

I guess this would involve standardizing the keywords that are used to describe the first three categories. So I guess (if I have followed Pietro's lesson well) you would end up with something that looks like this?
![image](https://user-images.githubusercontent.com/31648831/32290935-e49e580e-bf3b-11e7-87fc-f4e88b01a6aa.png)

At a later stage, I would also like to add further tags for specific elements, such as particular garments, objects, etc. So something like this, though I am not sure "term" would be right here?

![image](https://user-images.githubusercontent.com/31648831/32291024-2348358e-bf3c-11e7-8e7f-ba43bdb0f7f5.png)

Thanks!

**Comment by PietroLiuzzo** [comment]
@Gnisci you can type in your xml, instead of adding images, this helps a lot the readability and allows me to correct if needed

**Comment by PietroLiuzzo** [comment]
Let us split up this conversation which quickly went off topic. 

## keywords use in encoding of manuscripts
I do not want to direct your content choices in any way, but to add some practical principles for the encoding:
- you don't have to add any keywords to the manuscript description. These will theoretically have no msItems and a lot of decoNotes. there is no need to assign keywords if they are not needed. 
- One different point is weather we want to retrive all such manuscripts, then it might be useful to ad dd a generic keyword to describe this type like miniatureCollection or something similar. In the description it will be spelled out, but the keyword will facilitate retrievability of all and only these type of manuscripts. I would be strongly against a keyword like 'figure' which is semantically rather generic and servers no purpose which is not already supported by the current encoding.
- if the contents of the images are about hagiography, etc. and you think these manuscripts should come up if you click on that keywords, then please freely and inclusively add all those keywords  which you feel relevant and helpful.  

## `decoNote` and `decoDesc` encoding
We encode decorations in our catalogue records using these two elements. It would be a really great improvement for our schema to enlarge our taxonomy with art themes, iconographic types and styles. Artists (as `person`) Workshop (as `personGrp` with type workshop) and `date` can be encoded as usual instead using proper dates when possible, and/or a period attribution.
@jacopo, your guess is right, we need to expand the taxonomy to have these categories and to create authority files for each new term. if you are up for the task it would be a great way to get some hands on XML experience. a second step would be to go into the `decoDesc` and `decoNote` to use the terms. For this purpose I would probably simply use the element `rs`, but `term` is also fine, with a `@key` pointing to the taxonomy value. Stage 2 can be achieved in this way (and without the addition of any element). A easy encoding way would then be simply adding empty `term` elements with the correct `@key`. 

```xml
<decoNote type="miniature" xml:id="d1">
   <locus target="#14r"/>
    <desc>
        <persName type='artist' ref="PRS11251Erasmus"/>
         <date when="1456-03-02"/>
         <term key="#VerginAndChild"/>
         <term key="#Swords"/>
     </desc>
</decoNote>
```

of course as always the description can be given with a proper sentence and marked up, so that e.g. Vergin and Child needs not always be Vergin and Child, e.g.


```xml
<decoNote type="miniature" xml:id="d1">
   <locus target="#14r"/>
    <desc>
        <persName type='artist' ref="PRS11251Erasmus"/> painted this sometimes around
         <date notBefore="1456-03-01" notAfter="1456-03-31">March 1456</date>. This is a beautiful depiction of <term key="#VerginAndChild">Mary with Jesus as an infant</term>.
         The Angels hold <term key="#Swords"/>.
     </desc>
</decoNote>
```
When `term` contains text, this will be used, then not, the canonical title of the authority-file record will be printed.

so, an initial to do list

- [ ] update the taxonomy (@Gnisci, would you like to do that?)
- [ ] create the authority files related to each term  (@Gnisci, would you like to do that?)
- [ ] update the schema with the taxonomy values
- [ ] update the guidelines to reflect encoding practice
- [ ] test encode some miniatures using the taxonomy
- [ ] ensure the visualisation renders the encoding
- [ ] update the decoration list visualization to list the keywords used
- [ ] ensure the search allows to filter by these terms

**Comment by Gnisci** [comment]
update the taxonomy (@Gnisci, would you like to do that?)
create the authority files related to each term  (@Gnisci, would you like to do that?)

@PietroLiuzzo yes Pietro, happy to do this, but again, need to study your indications carefully before proceeding, and also going to have a look at other projects, so please give me some time to get back to you. Thanks.

**Comment by PietroLiuzzo** [comment]
cool @Gnisci, thanks!

# setting up
to carry out this task you can either 
1. edit files directly in github (click on the pencil/create new, etc.) which is software free, but I think does not give you all the freedom you might want to have
2. 
    - dowload github desktop, 
    - check out the repository with github desktop 
    - modify the xml files locally with 
              - the Atom editor 
              - simply using a plain text editor (blocco note, textedit, etc.).
     - commit the files with github desktop to the main repository
3. I do not remember how familiar you are with github, but the very best option would be to work as described in 2., but fork the repo and create a PR instead of pushing directly. But if you are not familiar with this than I do not think it is for this task strictly necessary 


# task description
There are two parts to this task:

## edit the taxonomy.xml file
You need to do is edit this file initially:
**https://github.com/BetaMasaheft/Authority-Files/blob/master/taxonomy.xml**

You will see that it is a very simply structured file. Art themes are at https://github.com/BetaMasaheft/Authority-Files/blob/master/taxonomy.xml#L248

You literally simply need to enter a new

````xml
<category>
                <catDesc>NEWTHEME</catDesc>
</category>
`````
inside the main `category`. This are actually keys, not spelled out names, they should not contain spaces or special characters.

## create the authority files
Then for each entry you will need to create an xml file in the authory-files repository. you can use in the live betamasaheft site the NEW button in the top bar. 
- select from the menu authority-file
- click new
- in the new page for ID enter EXACTELY the characters you entered in `catDesc` and in the title the spelled out name with any character you want (but better if very synthetical, so for the example above "New Theme" would be fine.
- create new and FOLLOW the instructions carefully.
- the newly created file can be enriched with bibliography, a paragraph description, anything you want to add that describe that concept category.

You can also proceed the other way around, so create the authority-file and then add the filename/ID in the taxonomy but it is VITAL that the work is carried out consistently and that there are no entries in the taxonomy without a file in authority-list or viceversa.

if you need more guidance, let me know, I am always here.

thanks a lot

**Comment by PietroLiuzzo** [comment]
- [x] Jacopo has been added to editos
- [x] schema updated to allow Jacopo
- [x] editing workflow script updated for Jacopo

**Comment by Gnisci** [comment]
So, I've entered, for instance, 
`<category>
      <catDesc>AgonyInTheGarden</catDesc>
</category>`

Then I go to create the authority file and type: 
![image](https://user-images.githubusercontent.com/31648831/32395649-4c0d4d22-c0e2-11e7-8f98-f2b507c3c30b.png)

But I get the following message:

![image](https://user-images.githubusercontent.com/31648831/32395580-015adea2-c0e2-11e7-8bae-1627acad1602.png)

**Comment by PietroLiuzzo** [comment]
thanks. yes at some point last week I had to remove that collection. now is there again. let me know if you find any other obstacle

**Comment by Gnisci** [comment]
Thank you for getting back to me @PietroLiuzzo , I've added two new categories:  
```
<category>
 <catDesc>Announciation</catDesc>
</category>
 <category>
<catDesc>ArrestOfJesus</catDesc>
</category>
```
But I am still getting an error message (like yesterday I am copy-pasting the CatDesc into ID:
![image](https://user-images.githubusercontent.com/31648831/32461196-5b3f6cf8-c335-11e7-94c3-5efd7c409c6c.png)

P.s.
How can I edit an existing authority file?

![image](https://user-images.githubusercontent.com/31648831/32461573-9763fbd0-c336-11e7-885c-a28ffdfa4f5f.png)

I see the title has been repeated twice for some reason. Can I just go through the process again: create a new authority file with that ID to edit the mistake?

Thank you.

**Comment by PietroLiuzzo** [comment]
The reason for the double visualization is not that the data is wrong. in this case I simply saved the file in the wrong folder (shame on me!) and thus created a double.
To edit a file, open it with your favourite method among the ones above from the authority-files git repository on your local machine, as you have opened and edited taxonomy.xml in the same repository, edit it, validate it and push it to git.

**Comment by PietroLiuzzo** [comment]
now I also fixed permissions so that you should be able to save the new files and I have fixed the cause of the doubles, which was not me actually but me as author of the syncing hook, which was saving in the wrong collection.

**Comment by PietroLiuzzo** [comment]
additionally, you should not be getting validation errors per email for the taxonomy, which was confusing.

**Comment by Gnisci** [comment]
I've finished updating a selection of Art Themes and I will now be adding 1) General description; and some 2) Secondary Bibliography for each of the themes. 

In the description I think it would be nice to include some references, for instance:

1.  In the description of the Doubting of Thomas, reference to the English,Ge'ez, and/or Greek versions of the relevant passage of John `  <ref cRef="urn:cts:greekLit:tlg0031.tlg001.perseus-grc1:14.3">John 20, 24-29</ref>` I tried adding as a test also `<ref cRef="urn:dts:betmas:LIT2075Number:21.8">Numbers 21:8</ref> ` which appears to have visualization problems (the Ge'ez text appear in a compressed box)

2.  I've tried pushing `<p> The scene illustrates a passage from
<ref cRef="urn:cts:greekLit:tlg0031.tlg001.perseus-grc1:14.3">John 20, 24-29</ref>
and shows <term key="#Thomas"/> putting his finger in the side of <term key="#Jesus"/>.</p>`, but I got an error, because I imagine I need to update the keys?

**Comment by Gnisci** [comment]
Dear @PietroLiuzzo,

Thanks for getting back to me on previous issues. Still some further points which emerge as I proceed with the encoding. I am currently adding PersName to the description of the themes as you suggested, so for instance: 
```
<p>
A miniature showing 
<persName ref="PRS5684JesusCh">Jesus</persName>
being arrested by the guards of the Temple
</p>
```
While one would certainly want users to have the possibility to locate all instances in which Jesus is featured, whether in writing or in art, it would also be beneficial to be able to distinguish between a PersName that features in a text and a PersName that appears in an artwork. Can I use att.typed (@type) to do this? And, if so, what would be the best way to encode this in `<listPerson>` in the relevant file?

Thank you

**Comment by PietroLiuzzo** [comment]
dear @Gnisci you do not need to encode twice an information.
if the `persName` or `placeName` is in a `decoNote` it is already different from a `persName` inside and `ab`, a `q` or children of a `msItem`, so there is no need to add a `@type`.
Where and how would you want this distinction to be visible? 
at the moment for a person
relations within a relation statement are shown in /persons/PRS4428Galawdew/analytic, the list of occurences in additions is displayed below the main body of the record, the full list of occurrences can be found in the advanced search with the contains reference to, is visible clicking on the small end beside every single persName in each manuscript description

**Comment by PietroLiuzzo** [comment]
and if the entity is in a relation, also the selector will allow to list a card for each related item.

**Comment by Gnisci** [comment]
Thank you for time, help, and patience.

**Comment by PietroLiuzzo** [comment]
persons, works, places and authority files now display a block below the main body with any available item containing a reference to that item in a decoNote.

**Comment by PietroLiuzzo** [comment]
the /decoration list now has filters. it is possible to select the type of decoration and or several type of entity attested within the decoNote. persons, works, places, keywords. these can of course be mixed.

**Comment by Gnisci** [comment]
Dear @PietroLiuzzo thank you so much for patiently putting up with me and for updating the schema to incorporate the new keywords I am implementing. Can I add new keywords to the schema to the ones you added as I move along or should I not touch it?

**Comment by PietroLiuzzo** [comment]
you are member of the group, you can checkout any repository, including the manuscript repository. there are no branches as far as I can see.

you can updated the schema. checkout the schema repository and edit the ODD (tei-betamasaheft.xml) you can search the part that interest you, which is under the elementSpec[@ident='term']. (l.344) 

Once the files and the taxonomy are there, you can add to that list the values like this

`````xml
<valItem ident="censer">
   <desc>censer</desc>
</valItem>
`````
Then in oxygen you have to run the transformation TEI ODD to RelaxNG XML which is there by default. it will create a folder called out where a file tei-betamasaheft.rng is saved. move that to the main schema folder replacing the old one and delete the out directory. then commit. It is possible that the file will not go directly to the app, although it should. in case it does not than I will upload it manually.

**Comment by Gnisci** [comment]
Thank you, @PietroLiuzzo  I will try to do that tomorrow, or in the weekend. In the meanwhile, I see other issues:

1) When I click on the art theme in the manuscript description I am redirected to `betamasaheft.eu/manuscripts/BNFet32/AT1034Tempietto` and obviously get an error because I believe I should be redirected to `betamasaheft.eu/authority-files/
`
2) Even keywords that have been inserted in the above method are giving some issues. E.g. if I type 
`<term key="censer"/>` and if I type `<term key="censer">censer</term>` I get the term but it does not lead me to the keyword

**Comment by PietroLiuzzo** [comment]
please @Gnisci open two separate new issues for the requirements in your points 1 and 2 in the last comment

**Comment by Gnisci** [comment]
@thea-m what do you think about using `<objectType>codex</objectType>`
in DecoNote when describing a character who is holding a book?

**Comment by PietroLiuzzo** [comment]
this would definitely bring unwanted ambiguities in the data. The currently discussed system of Art Themes and keywords can support this encoding without using objectType. This conversation is going into several lightly related topics. Please open new issues, I will close this now.
